/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUnshippedlistIndexRouteImport } from './routes/_authenticated/unshippedlist/index'
import { Route as AuthenticatedTemplatebulkIndexRouteImport } from './routes/_authenticated/templatebulk/index'
import { Route as AuthenticatedTemplateIndexRouteImport } from './routes/_authenticated/template/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedShippinglistIndexRouteImport } from './routes/_authenticated/shippinglist/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedQuotelistIndexRouteImport } from './routes/_authenticated/quotelist/index'
import { Route as AuthenticatedProductreportIndexRouteImport } from './routes/_authenticated/productreport/index'
import { Route as AuthenticatedProductionIndexRouteImport } from './routes/_authenticated/production/index'
import { Route as AuthenticatedOrderlistIndexRouteImport } from './routes/_authenticated/orderlist/index'
import { Route as AuthenticatedMonthlyreportIndexRouteImport } from './routes/_authenticated/monthlyreport/index'
import { Route as AuthenticatedIndustryreportIndexRouteImport } from './routes/_authenticated/industryreport/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCustomeryearlyreportIndexRouteImport } from './routes/_authenticated/customeryearlyreport/index'
import { Route as AuthenticatedCustomerlistIndexRouteImport } from './routes/_authenticated/customerlist/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAllordersIndexRouteImport } from './routes/_authenticated/allorders/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedProductionStatsRouteImport } from './routes/_authenticated/production/stats'
import { Route as AuthenticatedProductionReportRouteImport } from './routes/_authenticated/production/report'
import { Route as AuthenticatedProductionQcRouteImport } from './routes/_authenticated/production/qc'
import { Route as AuthenticatedProductionPlanRouteImport } from './routes/_authenticated/production/plan'
import { Route as AuthenticatedProductionOrderRouteImport } from './routes/_authenticated/production/order'
import { Route as AuthenticatedProductionMaterialRouteImport } from './routes/_authenticated/production/material'
import { Route as AuthenticatedProductionInboundRouteImport } from './routes/_authenticated/production/inbound'
import { Route as AuthenticatedFinanceVoucherRouteImport } from './routes/_authenticated/finance/voucher'
import { Route as AuthenticatedFinanceStatsRouteImport } from './routes/_authenticated/finance/stats'
import { Route as AuthenticatedFinancePaymentRouteImport } from './routes/_authenticated/finance/payment'
import { Route as AuthenticatedFinanceCollectionRouteImport } from './routes/_authenticated/finance/collection'
import { Route as AuthenticatedFinanceArRouteImport } from './routes/_authenticated/finance/ar'
import { Route as AuthenticatedFinanceApRouteImport } from './routes/_authenticated/finance/ap'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDictTypeIndexRouteImport } from './routes/_authenticated/dict/type/index'
import { Route as AuthenticatedDictDataIndexRouteImport } from './routes/_authenticated/dict/data/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnshippedlistIndexRoute =
  AuthenticatedUnshippedlistIndexRouteImport.update({
    id: '/unshippedlist/',
    path: '/unshippedlist/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatebulkIndexRoute =
  AuthenticatedTemplatebulkIndexRouteImport.update({
    id: '/templatebulk/',
    path: '/templatebulk/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplateIndexRoute =
  AuthenticatedTemplateIndexRouteImport.update({
    id: '/template/',
    path: '/template/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShippinglistIndexRoute =
  AuthenticatedShippinglistIndexRouteImport.update({
    id: '/shippinglist/',
    path: '/shippinglist/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedQuotelistIndexRoute =
  AuthenticatedQuotelistIndexRouteImport.update({
    id: '/quotelist/',
    path: '/quotelist/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductreportIndexRoute =
  AuthenticatedProductreportIndexRouteImport.update({
    id: '/productreport/',
    path: '/productreport/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionIndexRoute =
  AuthenticatedProductionIndexRouteImport.update({
    id: '/production/',
    path: '/production/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderlistIndexRoute =
  AuthenticatedOrderlistIndexRouteImport.update({
    id: '/orderlist/',
    path: '/orderlist/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonthlyreportIndexRoute =
  AuthenticatedMonthlyreportIndexRouteImport.update({
    id: '/monthlyreport/',
    path: '/monthlyreport/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustryreportIndexRoute =
  AuthenticatedIndustryreportIndexRouteImport.update({
    id: '/industryreport/',
    path: '/industryreport/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomeryearlyreportIndexRoute =
  AuthenticatedCustomeryearlyreportIndexRouteImport.update({
    id: '/customeryearlyreport/',
    path: '/customeryearlyreport/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomerlistIndexRoute =
  AuthenticatedCustomerlistIndexRouteImport.update({
    id: '/customerlist/',
    path: '/customerlist/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAllordersIndexRoute =
  AuthenticatedAllordersIndexRouteImport.update({
    id: '/allorders/',
    path: '/allorders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProductionStatsRoute =
  AuthenticatedProductionStatsRouteImport.update({
    id: '/production/stats',
    path: '/production/stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionReportRoute =
  AuthenticatedProductionReportRouteImport.update({
    id: '/production/report',
    path: '/production/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionQcRoute =
  AuthenticatedProductionQcRouteImport.update({
    id: '/production/qc',
    path: '/production/qc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionPlanRoute =
  AuthenticatedProductionPlanRouteImport.update({
    id: '/production/plan',
    path: '/production/plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionOrderRoute =
  AuthenticatedProductionOrderRouteImport.update({
    id: '/production/order',
    path: '/production/order',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionMaterialRoute =
  AuthenticatedProductionMaterialRouteImport.update({
    id: '/production/material',
    path: '/production/material',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionInboundRoute =
  AuthenticatedProductionInboundRouteImport.update({
    id: '/production/inbound',
    path: '/production/inbound',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceVoucherRoute =
  AuthenticatedFinanceVoucherRouteImport.update({
    id: '/finance/voucher',
    path: '/finance/voucher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceStatsRoute =
  AuthenticatedFinanceStatsRouteImport.update({
    id: '/finance/stats',
    path: '/finance/stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancePaymentRoute =
  AuthenticatedFinancePaymentRouteImport.update({
    id: '/finance/payment',
    path: '/finance/payment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceCollectionRoute =
  AuthenticatedFinanceCollectionRouteImport.update({
    id: '/finance/collection',
    path: '/finance/collection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceArRoute = AuthenticatedFinanceArRouteImport.update({
  id: '/finance/ar',
  path: '/finance/ar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceApRoute = AuthenticatedFinanceApRouteImport.update({
  id: '/finance/ap',
  path: '/finance/ap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictTypeIndexRoute =
  AuthenticatedDictTypeIndexRouteImport.update({
    id: '/dict/type/',
    path: '/dict/type/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictDataIndexRoute =
  AuthenticatedDictDataIndexRouteImport.update({
    id: '/dict/data/',
    path: '/dict/data/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/finance/ap': typeof AuthenticatedFinanceApRoute
  '/finance/ar': typeof AuthenticatedFinanceArRoute
  '/finance/collection': typeof AuthenticatedFinanceCollectionRoute
  '/finance/payment': typeof AuthenticatedFinancePaymentRoute
  '/finance/stats': typeof AuthenticatedFinanceStatsRoute
  '/finance/voucher': typeof AuthenticatedFinanceVoucherRoute
  '/production/inbound': typeof AuthenticatedProductionInboundRoute
  '/production/material': typeof AuthenticatedProductionMaterialRoute
  '/production/order': typeof AuthenticatedProductionOrderRoute
  '/production/plan': typeof AuthenticatedProductionPlanRoute
  '/production/qc': typeof AuthenticatedProductionQcRoute
  '/production/report': typeof AuthenticatedProductionReportRoute
  '/production/stats': typeof AuthenticatedProductionStatsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/allorders/': typeof AuthenticatedAllordersIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/customerlist/': typeof AuthenticatedCustomerlistIndexRoute
  '/customeryearlyreport/': typeof AuthenticatedCustomeryearlyreportIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/industryreport/': typeof AuthenticatedIndustryreportIndexRoute
  '/monthlyreport/': typeof AuthenticatedMonthlyreportIndexRoute
  '/orderlist/': typeof AuthenticatedOrderlistIndexRoute
  '/production/': typeof AuthenticatedProductionIndexRoute
  '/productreport/': typeof AuthenticatedProductreportIndexRoute
  '/quotelist/': typeof AuthenticatedQuotelistIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/shippinglist/': typeof AuthenticatedShippinglistIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/template/': typeof AuthenticatedTemplateIndexRoute
  '/templatebulk/': typeof AuthenticatedTemplatebulkIndexRoute
  '/unshippedlist/': typeof AuthenticatedUnshippedlistIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/dict/data/': typeof AuthenticatedDictDataIndexRoute
  '/dict/type/': typeof AuthenticatedDictTypeIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/finance/ap': typeof AuthenticatedFinanceApRoute
  '/finance/ar': typeof AuthenticatedFinanceArRoute
  '/finance/collection': typeof AuthenticatedFinanceCollectionRoute
  '/finance/payment': typeof AuthenticatedFinancePaymentRoute
  '/finance/stats': typeof AuthenticatedFinanceStatsRoute
  '/finance/voucher': typeof AuthenticatedFinanceVoucherRoute
  '/production/inbound': typeof AuthenticatedProductionInboundRoute
  '/production/material': typeof AuthenticatedProductionMaterialRoute
  '/production/order': typeof AuthenticatedProductionOrderRoute
  '/production/plan': typeof AuthenticatedProductionPlanRoute
  '/production/qc': typeof AuthenticatedProductionQcRoute
  '/production/report': typeof AuthenticatedProductionReportRoute
  '/production/stats': typeof AuthenticatedProductionStatsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/allorders': typeof AuthenticatedAllordersIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/customerlist': typeof AuthenticatedCustomerlistIndexRoute
  '/customeryearlyreport': typeof AuthenticatedCustomeryearlyreportIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/industryreport': typeof AuthenticatedIndustryreportIndexRoute
  '/monthlyreport': typeof AuthenticatedMonthlyreportIndexRoute
  '/orderlist': typeof AuthenticatedOrderlistIndexRoute
  '/production': typeof AuthenticatedProductionIndexRoute
  '/productreport': typeof AuthenticatedProductreportIndexRoute
  '/quotelist': typeof AuthenticatedQuotelistIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/shippinglist': typeof AuthenticatedShippinglistIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/template': typeof AuthenticatedTemplateIndexRoute
  '/templatebulk': typeof AuthenticatedTemplatebulkIndexRoute
  '/unshippedlist': typeof AuthenticatedUnshippedlistIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/dict/data': typeof AuthenticatedDictDataIndexRoute
  '/dict/type': typeof AuthenticatedDictTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/finance/ap': typeof AuthenticatedFinanceApRoute
  '/_authenticated/finance/ar': typeof AuthenticatedFinanceArRoute
  '/_authenticated/finance/collection': typeof AuthenticatedFinanceCollectionRoute
  '/_authenticated/finance/payment': typeof AuthenticatedFinancePaymentRoute
  '/_authenticated/finance/stats': typeof AuthenticatedFinanceStatsRoute
  '/_authenticated/finance/voucher': typeof AuthenticatedFinanceVoucherRoute
  '/_authenticated/production/inbound': typeof AuthenticatedProductionInboundRoute
  '/_authenticated/production/material': typeof AuthenticatedProductionMaterialRoute
  '/_authenticated/production/order': typeof AuthenticatedProductionOrderRoute
  '/_authenticated/production/plan': typeof AuthenticatedProductionPlanRoute
  '/_authenticated/production/qc': typeof AuthenticatedProductionQcRoute
  '/_authenticated/production/report': typeof AuthenticatedProductionReportRoute
  '/_authenticated/production/stats': typeof AuthenticatedProductionStatsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/allorders/': typeof AuthenticatedAllordersIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/customerlist/': typeof AuthenticatedCustomerlistIndexRoute
  '/_authenticated/customeryearlyreport/': typeof AuthenticatedCustomeryearlyreportIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/industryreport/': typeof AuthenticatedIndustryreportIndexRoute
  '/_authenticated/monthlyreport/': typeof AuthenticatedMonthlyreportIndexRoute
  '/_authenticated/orderlist/': typeof AuthenticatedOrderlistIndexRoute
  '/_authenticated/production/': typeof AuthenticatedProductionIndexRoute
  '/_authenticated/productreport/': typeof AuthenticatedProductreportIndexRoute
  '/_authenticated/quotelist/': typeof AuthenticatedQuotelistIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/shippinglist/': typeof AuthenticatedShippinglistIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/template/': typeof AuthenticatedTemplateIndexRoute
  '/_authenticated/templatebulk/': typeof AuthenticatedTemplatebulkIndexRoute
  '/_authenticated/unshippedlist/': typeof AuthenticatedUnshippedlistIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/dict/data/': typeof AuthenticatedDictDataIndexRoute
  '/_authenticated/dict/type/': typeof AuthenticatedDictTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/finance/ap'
    | '/finance/ar'
    | '/finance/collection'
    | '/finance/payment'
    | '/finance/stats'
    | '/finance/voucher'
    | '/production/inbound'
    | '/production/material'
    | '/production/order'
    | '/production/plan'
    | '/production/qc'
    | '/production/report'
    | '/production/stats'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/allorders/'
    | '/apps/'
    | '/chats/'
    | '/customerlist/'
    | '/customeryearlyreport/'
    | '/help-center/'
    | '/industryreport/'
    | '/monthlyreport/'
    | '/orderlist/'
    | '/production/'
    | '/productreport/'
    | '/quotelist/'
    | '/settings/'
    | '/shippinglist/'
    | '/tasks/'
    | '/template/'
    | '/templatebulk/'
    | '/unshippedlist/'
    | '/users/'
    | '/dict/data/'
    | '/dict/type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/finance/ap'
    | '/finance/ar'
    | '/finance/collection'
    | '/finance/payment'
    | '/finance/stats'
    | '/finance/voucher'
    | '/production/inbound'
    | '/production/material'
    | '/production/order'
    | '/production/plan'
    | '/production/qc'
    | '/production/report'
    | '/production/stats'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/allorders'
    | '/apps'
    | '/chats'
    | '/customerlist'
    | '/customeryearlyreport'
    | '/help-center'
    | '/industryreport'
    | '/monthlyreport'
    | '/orderlist'
    | '/production'
    | '/productreport'
    | '/quotelist'
    | '/settings'
    | '/shippinglist'
    | '/tasks'
    | '/template'
    | '/templatebulk'
    | '/unshippedlist'
    | '/users'
    | '/dict/data'
    | '/dict/type'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/finance/ap'
    | '/_authenticated/finance/ar'
    | '/_authenticated/finance/collection'
    | '/_authenticated/finance/payment'
    | '/_authenticated/finance/stats'
    | '/_authenticated/finance/voucher'
    | '/_authenticated/production/inbound'
    | '/_authenticated/production/material'
    | '/_authenticated/production/order'
    | '/_authenticated/production/plan'
    | '/_authenticated/production/qc'
    | '/_authenticated/production/report'
    | '/_authenticated/production/stats'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/allorders/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/customerlist/'
    | '/_authenticated/customeryearlyreport/'
    | '/_authenticated/help-center/'
    | '/_authenticated/industryreport/'
    | '/_authenticated/monthlyreport/'
    | '/_authenticated/orderlist/'
    | '/_authenticated/production/'
    | '/_authenticated/productreport/'
    | '/_authenticated/quotelist/'
    | '/_authenticated/settings/'
    | '/_authenticated/shippinglist/'
    | '/_authenticated/tasks/'
    | '/_authenticated/template/'
    | '/_authenticated/templatebulk/'
    | '/_authenticated/unshippedlist/'
    | '/_authenticated/users/'
    | '/_authenticated/dict/data/'
    | '/_authenticated/dict/type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unshippedlist/': {
      id: '/_authenticated/unshippedlist/'
      path: '/unshippedlist'
      fullPath: '/unshippedlist/'
      preLoaderRoute: typeof AuthenticatedUnshippedlistIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templatebulk/': {
      id: '/_authenticated/templatebulk/'
      path: '/templatebulk'
      fullPath: '/templatebulk/'
      preLoaderRoute: typeof AuthenticatedTemplatebulkIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/template/': {
      id: '/_authenticated/template/'
      path: '/template'
      fullPath: '/template/'
      preLoaderRoute: typeof AuthenticatedTemplateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shippinglist/': {
      id: '/_authenticated/shippinglist/'
      path: '/shippinglist'
      fullPath: '/shippinglist/'
      preLoaderRoute: typeof AuthenticatedShippinglistIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/quotelist/': {
      id: '/_authenticated/quotelist/'
      path: '/quotelist'
      fullPath: '/quotelist/'
      preLoaderRoute: typeof AuthenticatedQuotelistIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productreport/': {
      id: '/_authenticated/productreport/'
      path: '/productreport'
      fullPath: '/productreport/'
      preLoaderRoute: typeof AuthenticatedProductreportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/': {
      id: '/_authenticated/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof AuthenticatedProductionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orderlist/': {
      id: '/_authenticated/orderlist/'
      path: '/orderlist'
      fullPath: '/orderlist/'
      preLoaderRoute: typeof AuthenticatedOrderlistIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monthlyreport/': {
      id: '/_authenticated/monthlyreport/'
      path: '/monthlyreport'
      fullPath: '/monthlyreport/'
      preLoaderRoute: typeof AuthenticatedMonthlyreportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industryreport/': {
      id: '/_authenticated/industryreport/'
      path: '/industryreport'
      fullPath: '/industryreport/'
      preLoaderRoute: typeof AuthenticatedIndustryreportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customeryearlyreport/': {
      id: '/_authenticated/customeryearlyreport/'
      path: '/customeryearlyreport'
      fullPath: '/customeryearlyreport/'
      preLoaderRoute: typeof AuthenticatedCustomeryearlyreportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customerlist/': {
      id: '/_authenticated/customerlist/'
      path: '/customerlist'
      fullPath: '/customerlist/'
      preLoaderRoute: typeof AuthenticatedCustomerlistIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/allorders/': {
      id: '/_authenticated/allorders/'
      path: '/allorders'
      fullPath: '/allorders/'
      preLoaderRoute: typeof AuthenticatedAllordersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/production/stats': {
      id: '/_authenticated/production/stats'
      path: '/production/stats'
      fullPath: '/production/stats'
      preLoaderRoute: typeof AuthenticatedProductionStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/report': {
      id: '/_authenticated/production/report'
      path: '/production/report'
      fullPath: '/production/report'
      preLoaderRoute: typeof AuthenticatedProductionReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/qc': {
      id: '/_authenticated/production/qc'
      path: '/production/qc'
      fullPath: '/production/qc'
      preLoaderRoute: typeof AuthenticatedProductionQcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/plan': {
      id: '/_authenticated/production/plan'
      path: '/production/plan'
      fullPath: '/production/plan'
      preLoaderRoute: typeof AuthenticatedProductionPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/order': {
      id: '/_authenticated/production/order'
      path: '/production/order'
      fullPath: '/production/order'
      preLoaderRoute: typeof AuthenticatedProductionOrderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/material': {
      id: '/_authenticated/production/material'
      path: '/production/material'
      fullPath: '/production/material'
      preLoaderRoute: typeof AuthenticatedProductionMaterialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/inbound': {
      id: '/_authenticated/production/inbound'
      path: '/production/inbound'
      fullPath: '/production/inbound'
      preLoaderRoute: typeof AuthenticatedProductionInboundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/voucher': {
      id: '/_authenticated/finance/voucher'
      path: '/finance/voucher'
      fullPath: '/finance/voucher'
      preLoaderRoute: typeof AuthenticatedFinanceVoucherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/stats': {
      id: '/_authenticated/finance/stats'
      path: '/finance/stats'
      fullPath: '/finance/stats'
      preLoaderRoute: typeof AuthenticatedFinanceStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/payment': {
      id: '/_authenticated/finance/payment'
      path: '/finance/payment'
      fullPath: '/finance/payment'
      preLoaderRoute: typeof AuthenticatedFinancePaymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/collection': {
      id: '/_authenticated/finance/collection'
      path: '/finance/collection'
      fullPath: '/finance/collection'
      preLoaderRoute: typeof AuthenticatedFinanceCollectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/ar': {
      id: '/_authenticated/finance/ar'
      path: '/finance/ar'
      fullPath: '/finance/ar'
      preLoaderRoute: typeof AuthenticatedFinanceArRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/ap': {
      id: '/_authenticated/finance/ap'
      path: '/finance/ap'
      fullPath: '/finance/ap'
      preLoaderRoute: typeof AuthenticatedFinanceApRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dict/type/': {
      id: '/_authenticated/dict/type/'
      path: '/dict/type'
      fullPath: '/dict/type/'
      preLoaderRoute: typeof AuthenticatedDictTypeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dict/data/': {
      id: '/_authenticated/dict/data/'
      path: '/dict/data'
      fullPath: '/dict/data/'
      preLoaderRoute: typeof AuthenticatedDictDataIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedFinanceApRoute: typeof AuthenticatedFinanceApRoute
  AuthenticatedFinanceArRoute: typeof AuthenticatedFinanceArRoute
  AuthenticatedFinanceCollectionRoute: typeof AuthenticatedFinanceCollectionRoute
  AuthenticatedFinancePaymentRoute: typeof AuthenticatedFinancePaymentRoute
  AuthenticatedFinanceStatsRoute: typeof AuthenticatedFinanceStatsRoute
  AuthenticatedFinanceVoucherRoute: typeof AuthenticatedFinanceVoucherRoute
  AuthenticatedProductionInboundRoute: typeof AuthenticatedProductionInboundRoute
  AuthenticatedProductionMaterialRoute: typeof AuthenticatedProductionMaterialRoute
  AuthenticatedProductionOrderRoute: typeof AuthenticatedProductionOrderRoute
  AuthenticatedProductionPlanRoute: typeof AuthenticatedProductionPlanRoute
  AuthenticatedProductionQcRoute: typeof AuthenticatedProductionQcRoute
  AuthenticatedProductionReportRoute: typeof AuthenticatedProductionReportRoute
  AuthenticatedProductionStatsRoute: typeof AuthenticatedProductionStatsRoute
  AuthenticatedAllordersIndexRoute: typeof AuthenticatedAllordersIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCustomerlistIndexRoute: typeof AuthenticatedCustomerlistIndexRoute
  AuthenticatedCustomeryearlyreportIndexRoute: typeof AuthenticatedCustomeryearlyreportIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedIndustryreportIndexRoute: typeof AuthenticatedIndustryreportIndexRoute
  AuthenticatedMonthlyreportIndexRoute: typeof AuthenticatedMonthlyreportIndexRoute
  AuthenticatedOrderlistIndexRoute: typeof AuthenticatedOrderlistIndexRoute
  AuthenticatedProductionIndexRoute: typeof AuthenticatedProductionIndexRoute
  AuthenticatedProductreportIndexRoute: typeof AuthenticatedProductreportIndexRoute
  AuthenticatedQuotelistIndexRoute: typeof AuthenticatedQuotelistIndexRoute
  AuthenticatedShippinglistIndexRoute: typeof AuthenticatedShippinglistIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTemplateIndexRoute: typeof AuthenticatedTemplateIndexRoute
  AuthenticatedTemplatebulkIndexRoute: typeof AuthenticatedTemplatebulkIndexRoute
  AuthenticatedUnshippedlistIndexRoute: typeof AuthenticatedUnshippedlistIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedDictDataIndexRoute: typeof AuthenticatedDictDataIndexRoute
  AuthenticatedDictTypeIndexRoute: typeof AuthenticatedDictTypeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedFinanceApRoute: AuthenticatedFinanceApRoute,
  AuthenticatedFinanceArRoute: AuthenticatedFinanceArRoute,
  AuthenticatedFinanceCollectionRoute: AuthenticatedFinanceCollectionRoute,
  AuthenticatedFinancePaymentRoute: AuthenticatedFinancePaymentRoute,
  AuthenticatedFinanceStatsRoute: AuthenticatedFinanceStatsRoute,
  AuthenticatedFinanceVoucherRoute: AuthenticatedFinanceVoucherRoute,
  AuthenticatedProductionInboundRoute: AuthenticatedProductionInboundRoute,
  AuthenticatedProductionMaterialRoute: AuthenticatedProductionMaterialRoute,
  AuthenticatedProductionOrderRoute: AuthenticatedProductionOrderRoute,
  AuthenticatedProductionPlanRoute: AuthenticatedProductionPlanRoute,
  AuthenticatedProductionQcRoute: AuthenticatedProductionQcRoute,
  AuthenticatedProductionReportRoute: AuthenticatedProductionReportRoute,
  AuthenticatedProductionStatsRoute: AuthenticatedProductionStatsRoute,
  AuthenticatedAllordersIndexRoute: AuthenticatedAllordersIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCustomerlistIndexRoute: AuthenticatedCustomerlistIndexRoute,
  AuthenticatedCustomeryearlyreportIndexRoute:
    AuthenticatedCustomeryearlyreportIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedIndustryreportIndexRoute: AuthenticatedIndustryreportIndexRoute,
  AuthenticatedMonthlyreportIndexRoute: AuthenticatedMonthlyreportIndexRoute,
  AuthenticatedOrderlistIndexRoute: AuthenticatedOrderlistIndexRoute,
  AuthenticatedProductionIndexRoute: AuthenticatedProductionIndexRoute,
  AuthenticatedProductreportIndexRoute: AuthenticatedProductreportIndexRoute,
  AuthenticatedQuotelistIndexRoute: AuthenticatedQuotelistIndexRoute,
  AuthenticatedShippinglistIndexRoute: AuthenticatedShippinglistIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTemplateIndexRoute: AuthenticatedTemplateIndexRoute,
  AuthenticatedTemplatebulkIndexRoute: AuthenticatedTemplatebulkIndexRoute,
  AuthenticatedUnshippedlistIndexRoute: AuthenticatedUnshippedlistIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedDictDataIndexRoute: AuthenticatedDictDataIndexRoute,
  AuthenticatedDictTypeIndexRoute: AuthenticatedDictTypeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
